### ISSUE TITLE
Running example data does not work due to KeyError: X_root

### ISSUE THREAD

**Issue by ddemaeyer** [czbiohub/excellxgene#11]
>pip install excellxgene==2.6.3
....
Successfully installed excellxgene-2.6.3

> excellxgene launch example-dataset/pbmc500.h5ad
Configuring multiprocessing spawner...
[cellxgene] Starting the CLI...
[cellxgene] Loading data from pbmc500.h5ad.
Loading and precomputing layers necessary for fast differential expression and reembedding...
Layer X ...
Finished loading the data.
Validating and initializing...
KeyError: 'X_root'

Error persists in latest version 2.7.4

**Comment by atarashansky** [comment]
Hi,

thanks for reporting this. While I take a look into this, can you try doing this with version 2.7.4?

best,
Alec

**Comment by atarashansky** [comment]
Hey, thanks for reporting this.

I’ll take a look and get back to you!

**Comment by atarashansky** [comment]
Hi there,

Please upgrade to `2.7.5` and try again. It should be fixed. Keep in mind that pbmc500 is a completely empty dataset (i.e. no UMAP embedding) so you'll see a blank screen ( attached image below). To generate a UMAP, you'll need to preprocess and embed using the reembedding dialog (second image attached below). Closing this issue for now, but feel free to reopen if you have any other related questions, concerns, or issues.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16548075/165392767-52a9b26b-f1b7-4f25-b073-48ad7d2f49ec.png">

<img width="910" alt="image" src="https://user-images.githubusercontent.com/16548075/165392848-a4a3ebda-2e43-4dcd-8656-7afa0cb7dd70.png">
