### ISSUE TITLE
[BUG] FileNotFoundError upon launching example dataset

### ISSUE THREAD

**Issue by mdmanurung** [czbiohub/excellxgene#2]
**Describe the bug**

An unexpected HTTP error appeared on the browser upon launching example dataset. 

```
ERROR:backend.server.app.app:Exception on /api/v0.2/schema [GET]
FileNotFoundError: [Errno 2] No such file or directory: 'EX3BW7XY/obs/obs\\name_0.p'
```

**To Reproduce**
1. Clone the excellgene repo and `cd` into the folder.
2. In command prompt, run `excellxgene launch example-dataset/pbmc3k.h5ad`

**Expected behavior**

I expect to access excellxgene instance via my browser.

**Screenshots**

**Version (please complete the following information):**
 - Desktop or hosted?: Desktop
 - Browser (if hosted) [e.g. chrome, safari]: Chrome
 - Version [e.g. 0.13.0]: 2.3.2

**Additional context**
I am using Windows 10.

**Comment by atarashansky** [comment]
Fixed in v2.3.4!
