### ISSUE TITLE
[BUG] Blank screen after selecting genes to make scatterplots

### ISSUE THREAD

**Issue by mdmanurung** [czbiohub/excellxgene#3]
**Describe the bug**
When I select two genes to make a scatterplot, my browser display went blank.

**To Reproduce**
1. Launch data
2. Select one gene each for x and y

**Expected behavior**
I expect to see the scatterplots of both genes in the lower-left corner.

**Screenshots**

**Version (please complete the following information):**
 - Desktop or hosted?: Desktop
 - Browser (if hosted) [e.g. chrome, safari]: Chrome
 - Version [e.g. 0.13.0]: 2.3.4

**Additional context**

**Comment by atarashansky** [comment]
Fixed in v2.3.5! Thanks for catching this.

**Comment by mdmanurung** [comment]
Thanks a lot for your rapid fix. It's relieving to see that this software is maintained well.
